app = "sureword"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 1935
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    handlers = []
    port = 1935

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
