listen              1935;
max_connections     1000;
srs_log_tank        console;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        /tmp/srs/hls;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_fragment    2;
        hls_window      10;
        hls_dispose     30;
    }

    http_hooks {
        enabled         on;
        on_publish      http://127.0.0.1:3000/srs/hooks/on_publish;
        on_unpublish    http://127.0.0.1:3000/srs/hooks/on_unpublish;
    }
}
