ALTER TABLE print_media ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE print_media ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
ALTER TABLE music ADD COLUMN IF NOT EXISTS play_count INTEGER DEFAULT 0;
